apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
  labels:
    app: hello-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      name: hello-spring
      labels:
        app: hello-spring
    spec:
      containers:
        - name: hello-spring
          image: hello-spring
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
